services:
  basic_rag_app:
    build: .
    container_name: basic_rag_app
    ports:
      - "7850:7850"  
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 7850
      EMB_MODEL_NAME: "${EMB_MODEL_NAME}"
      PINECONE_API_KEY: "${PINECONE_API_KEY}"
      PINECONE_INDEX_NAME: "${PINECONE_INDEX_NAME}"
      PINECONE_NAMESPACE: "${PINECONE_NAMESPACE}"
      SARVAM_API_KEY: "${SARVAM_API_KEY}"
      PINECONE_CLOUD: "${PINECONE_CLOUD}"
      AWS_REGION: "${AWS_REGION}"

    command: ["--type", "basic"]
    volumes:
      - .:/app  # Maps your current directory to the app folder in the container
    networks:
      - rag_network

  agentic_rag_app:
    build: .
    container_name: agentic_rag_app
    ports:
      - "7860:7860"  
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 7860
      EMB_MODEL_NAME: "${EMB_MODEL_NAME}"
      PINECONE_API_KEY: "${PINECONE_API_KEY}"
      PINECONE_INDEX_NAME: "${PINECONE_INDEX_NAME}"
      PINECONE_NAMESPACE: "${PINECONE_NAMESPACE}"
      SARVAM_API_KEY: "${SARVAM_API_KEY}"
      PINECONE_CLOUD: "${PINECONE_CLOUD}"
      AWS_REGION: "${AWS_REGION}"
      TAVILY_API_KEY: "${TAVILY_API_KEY}"
      
    command: ["--type", "agentic"]
    volumes:
      - .:/app  # Maps your current directory to the app folder in the container
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
